# Generated by Django 3.2 on 2021-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
